version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/usr/local/bin/dockerized-rest-api/wait-for-mysql.sh", "db", 
      "/usr/local/bin/dockerized-rest-api/init.sh"]

  db:
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: dockerized-rest-api_root_pass
      MYSQL_DATABASE: dockerized-rest-api_db
      MYSQL_USER: dockerized-rest-api_user
      MYSQL_PASSWORD: dockerized-rest-api_pass
    ports:
      - 3306:3306
    restart: always
